---
language: php
php: 7.3
addons:
    apt:
        packages:
            - language-pack-fr
install:
    - composer install --no-progress
    - yarn install
script:
    - grunt lint
    - grunt test
