---
language: php
php: 7.1
addons:
    apt:
        packages:
            - language-pack-fr
install:
    - composer install --no-progress
    - yarn install
script:
    - grunt lint
    - composer exec -v
        phpunit
